[package]
name = "servo-media-examples"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description.workspace = true
publish = false

[dependencies]
euclid = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
freetype-sys = { workspace = true, features = ["bundled"] } # used only to force bundled to make it standalone for CI
servo-media = { workspace = true }
servo-media-auto = { workspace = true }
servo-media-dummy = { workspace = true }
