const urls = {
  invalid: [
    "",
    "not-valid",
  ],
  opaque: [
    "about:blank",
    "data:text/plain,opaque",
    "weird-protocol:whatever",
    "weird-hierarchical-protocol://host/path?etc",
    "blob:weird-protocol:whatever",
    "blob:weird-hierarchical-protocol://host/path?etc",
  ],
  tuple: [
    "http://site.example",
    "https://site.example",
    "https://site.example:123",
    "http://sub.site.example",
    "https://sub.site.example",
    "https://sub.site.example:123",
    "https://xn--mlauted-m2a.example",
    "ftp://ftp.example",
    "ws://ws.example",
    "wss://wss.example",
    "https://trailing.slash/",
    "https://user:pass@site.example",
    "https://has.a.port:1234/and/path",
    "https://ümlauted.example",
    "file:///path/to/a/file.txt",
    "blob:https://example.com/some-guid",
    "ftp://example.com/",
    "https://example.com/path?query#fragment",
    "https://127.0.0.1/",
    "https://[::1]/",
  ],
};
