// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.text.baseline.invalid
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.textBaseline = 'top';
  ctx.textBaseline = 'bogus';
  _assertSame(ctx.textBaseline, 'top', "ctx.textBaseline", "'top'");

  ctx.textBaseline = 'top';
  ctx.textBaseline = 'MIDDLE';
  _assertSame(ctx.textBaseline, 'top', "ctx.textBaseline", "'top'");

  ctx.textBaseline = 'top';
  ctx.textBaseline = 'middle ';
  _assertSame(ctx.textBaseline, 'top', "ctx.textBaseline", "'top'");

  ctx.textBaseline = 'top';
  ctx.textBaseline = 'middle\0';
  _assertSame(ctx.textBaseline, 'top', "ctx.textBaseline", "'top'");
  t.done();
});
done();
