# The `minSdk` configuration affects both the `NDK` version we require,
# and the `minSdk` version for the gradle build.
# This value should only be bumped if necessary, and after discussion
# on zulip, since it directly affects the amount of people able to use
# servo on android.
# ATTENTION - READ THE COMMENT ABOVE, if the minSdk value below is changed.
android.minSdk=29
