package servo:dom@0.1.0;

interface console {
    log: func(message: string);
    error: func(message: string);
}

interface document {
    resource element {
        set-attribute: func(name: string, value: string);
        get-attribute: func(name: string) -> option<string>;

        get-property: func(name: string) -> string;
        set-property: func(name: string, value: string);

        append-child: func(child: borrow<element>);
        insert-before: func(child: borrow<element>, reference-child: borrow<element>);
        remove-child: func(child: borrow<element>);
        set-text-content: func(text: string);
        get-text-content: func() -> string;
        add-event-listener: func(event-type: string, handler-id: string);
        remove-event-listener: func(event-type: string, handler-id: string);
    }

    create-element: func(tag: string) -> result<element, string>;
    get-body: func() -> result<element, string>;
    get-element-by-id: func(id: string) -> result<element, string>;
    query-selector: func(selector: string) -> option<element>;
}

world app {
    import console;
    import document;

    export run: func();
    export on-event: func(handler-id: string, event-type: string);
}
