namespace ServoApp
{
    [default_interface]
    runtimeclass BrowserPage : Windows.UI.Xaml.Controls.Page
    {
        BrowserPage();
        Windows.Foundation.Collections.IObservableVector<IInspectable> ConsoleLogs{ get; };
        Windows.Foundation.Collections.IObservableVector<IInspectable> Bookmarks{ get; };
    }

    runtimeclass ConsoleLog
    {
        ConsoleLog(Windows.UI.Color glyphColor, String glyph, String body, String source);
        Windows.UI.Xaml.Media.SolidColorBrush GlyphColor{ get; };
        String Glyph{ get; };
        String Body{ get; };
        String Source{ get; };
    }

    runtimeclass Bookmark
    {
        Bookmark(String name, String url);
        String Name{ get; };
        String Url{ get; };
    }
}
