// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.canvas.context.type.replace
// Description:Interface methods can be overridden
// Note:<p class="notes">Defined in "Web IDL" (draft)

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Interface methods can be overridden");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  var fillRect = self.OffscreenCanvasRenderingContext2D.prototype.fillRect;
  self.OffscreenCanvasRenderingContext2D.prototype.fillRect = function (x, y, w, h)
  {
      this.fillStyle = '#0f0';
      fillRect.call(this, x, y, w, h);
  };
  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 0, 100, 50);
  _assertPixel(canvas, 50,25, 0,255,0,255);
  t.done();
});
done();
