# This image for WebKitGTK tests is based on Debian stable to ensure binary
# compatibility with ToT/trunk built-products from build.webkit.org bots.
# See https://github.com/web-platform-tests/wpt/pull/18595#issuecomment-537267080
FROM debian:10

# No interactive frontend during docker build
ENV DEBIAN_FRONTEND=noninteractive \
    DEBCONF_NONINTERACTIVE_SEEN=true

# Install general requirements not in the base image
RUN apt-get -qqy update \
  && apt-get -qqy install \
    bzip2 \
    ca-certificates \
    dbus-x11 \
    earlyoom \
    fluxbox \
    gdebi \
    git \
    locales \
    pulseaudio \
    python \
    python-pip \
    python-virtualenv \
    tzdata \
    sudo \
    unzip \
    wget \
    xvfb \
    git-core

# Configure buster-wpt-webkit-updates repository
RUN apt-key adv --fetch-keys https://webkitgtk.org/debian/apt.key
RUN printf 'deb [arch=amd64] https://webkitgtk.org/debian buster-wpt-webkit-updates main' \
    > /etc/apt/sources.list.d/webkitgtk.list
RUN printf 'Package: *\nPin: origin webkitgtk.org\nPin-Priority: 1999' \
    > /etc/apt/preferences.d/99webkitgtk

# Update and upgrade
RUN apt-get update \
  && apt-get -y upgrade

# Install webkit packages from https://webkitgtk.org/debian
RUN apt-get install -y -t buster-wpt-webkit-updates webkit2gtk-driver

# Set the timezone
ENV TZ "UTC"
RUN echo "${TZ}" > /etc/timezone \
  && dpkg-reconfigure --frontend noninteractive tzdata

# Set the locale
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
  && dpkg-reconfigure --frontend noninteractive locales
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN useradd test \
         --shell /bin/bash  \
         --create-home \
  && usermod -a -G sudo test \
  && echo 'ALL ALL = (ALL) NOPASSWD: ALL' >> /etc/sudoers \
  && echo 'test:secret' | chpasswd

ENV SCREEN_WIDTH 1280
ENV SCREEN_HEIGHT 1024
ENV SCREEN_DEPTH 24
ENV DISPLAY :99.0

USER test

WORKDIR /home/test

# Remove information on how to use sudo on login
RUN sudo echo ""

RUN mkdir -p /home/test/artifacts
RUN mkdir -p /home/test/bin

ENV PATH="/home/test/bin:/home/test/.local/bin:${PATH}"

WORKDIR /home/test/

COPY .bashrc /home/test/.bashrc

COPY start.sh /home/test/start.sh
COPY retry.py /home/test/bin/retry
