namespace ServoApp {

  delegate void EventDelegate();
  delegate void HistoryChangedDelegate(Boolean back, Boolean forward);

  runtimeclass ServoControl : Windows.UI.Xaml.Controls.Control {
      ServoControl();
      void GoBack();
      void GoForward();
      void Reload();
      void Stop();
      Windows.Foundation.Uri LoadURIOrSearch(String url);
      void SetTransientMode(Boolean transient);
      void SetArgs(String args);
      void Shutdown();
      event EventDelegate OnLoadStarted;
      event EventDelegate OnLoadEnded;
      event EventDelegate OnCaptureGesturesStarted;
      event EventDelegate OnCaptureGesturesEnded;
      event HistoryChangedDelegate OnHistoryChanged;
      event Windows.Foundation.EventHandler<String> OnTitleChanged;
      event Windows.Foundation.EventHandler<String> OnURLChanged;
}
} // namespace ServoApp
