interface mixin InterestInvokerElement {
  [CEReactions,Reflect=interesttarget] attribute Element? interestTargetElement;
};

HTMLInputElement includes InterestInvokerElement;
HTMLButtonElement includes InterestInvokerElement;
HTMLAnchorElement includes InterestInvokerElement;