interface mixin InvokerElement {
  [CEReactions,Reflect=invoketarget] attribute Element? commandForElement;
  [CEReactions,Reflect=invokeaction] attribute DOMString command;
};

interface CommandEvent : Event {
    constructor(DOMString type, optional CommandEventInit eventInitDict = {});
    readonly attribute Element? invoker;
    readonly attribute DOMString command;
};

dictionary CommandEventInit : EventInit {
    Element? invoker = null;
    DOMString command = "";
};
