dictionary HTMLMediaStreamConstraints {
  MediaTrackConstraintSet video;
  MediaTrackConstraintSet audio;
};

[Exposed=Window]
interface HTMLUserMediaElement : HTMLElement {
  [HTMLConstructor] constructor();

  [CEReactions] attribute DOMString type;
  attribute EventHandler onstream;
  attribute EventHandler oncancel;
  attribute EventHandler onerror;

  static boolean isTypeSupported(DOMString type);

  readonly attribute MediaStream? stream;
  readonly attribute DOMException? error;

  undefined setConstraints(optional HTMLMediaStreamConstraints constraints = {});

  readonly attribute boolean isValid;
  readonly attribute InPagePermissionMixinBlockerReason invalidReason;
  readonly attribute PermissionState initialPermissionStatus;
  readonly attribute PermissionState permissionStatus;

  attribute EventHandler onpromptaction;
  attribute EventHandler onpromptdismiss;
  attribute EventHandler onvalidationstatuschange;
};
