// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.reset.state.shadow_blur
// Description:check that the state is reset
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("check that the state is reset");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  const default_value = ctx.shadowBlur;

  ctx.shadowBlur = 10.0;
  _assert(ctx.shadowBlur == 10.0, "ctx.shadowBlur == 10.0");

  ctx.reset();
  _assert(ctx.shadowBlur == default_value, "ctx.shadowBlur == default_value");
  t.done();
});
done();
