# Fenced frame HTML body. Generated by a Python file to avoid having quotes in
# the injected script escaped, which the test server does to *.html files.
def main(request, response):
    response.status = (200, b"OK")
    response.headers.set(b"Content-Type", b"text/html")
    response.headers.set(b"Supports-Loading-Mode", b"fenced-frame")

    return """
        <!DOCTYPE html>
        <html>
        <head>
        <!--- Allow injected scripts to use functions in fledge-util.sub.js --->
        <base href="..">
        <script src="/resources/testharness.js"></script>
        <script src="/common/utils.js"></script>
        <script src="resources/fledge-util.sub.js"></script>
        </head>
        <body>
        <script>
        {{GET[script]}}
        </script>
        </body>
        </html>
     """


