// Copyright (c) 2014 Marshall A. Greenblatt. All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:
//
//    * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//    * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//    * Neither the name of Google Inc. nor the name Chromium Embedded
// Framework nor the names of its contributors may be used to endorse
// or promote products derived from this software without specific prior
// written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool and should not be edited
// by hand. See the translator.README.txt file in the tools directory for
// more information.
//

#![allow(non_snake_case, unused_imports)]

use eutil;
use interfaces;
use types;
use wrappers::CefWrap;

use libc;
use std::collections::HashMap;
use std::ptr;

//
// A request context provides request handling for a set of related browser
// objects. A request context is specified when creating a new browser object
// via the cef_browser_host_t static factory functions. Browser objects with
// different request contexts will never be hosted in the same render process.
// Browser objects with the same request context may or may not be hosted in the
// same render process depending on the process model. Browser objects created
// indirectly via the JavaScript window.open function or targeted links will
// share the same render process and the same request context as the source
// browser. When running in single-process mode there is only a single render
// process (the main process) and so all browsers created in single-process mode
// will share the same request context. This will be the first request context
// passed into a cef_browser_host_t static factory function and all other
// request context objects will be ignored.
//
#[repr(C)]
pub struct _cef_request_context_t {
  //
  // Base structure.
  //
  pub base: types::cef_base_t,

  //
  // Returns true (1) if this object is pointing to the same context as |that|
  // object.
  //
  pub is_same: Option<extern "C" fn(this: *mut cef_request_context_t,
      other: *mut interfaces::cef_request_context_t) -> libc::c_int>,

  //
  // Returns true (1) if this object is the global context.
  //
  pub is_global: Option<extern "C" fn(
      this: *mut cef_request_context_t) -> libc::c_int>,

  //
  // Returns the handler for this context if any.
  //
  pub get_handler: Option<extern "C" fn(
      this: *mut cef_request_context_t) -> *mut interfaces::cef_request_context_handler_t>,

  //
  // The reference count. This will only be present for Rust instances!
  //
  pub ref_count: uint,

  //
  // Extra data. This will only be present for Rust instances!
  //
  pub extra: u8,
} 

pub type cef_request_context_t = _cef_request_context_t;


//
// A request context provides request handling for a set of related browser
// objects. A request context is specified when creating a new browser object
// via the cef_browser_host_t static factory functions. Browser objects with
// different request contexts will never be hosted in the same render process.
// Browser objects with the same request context may or may not be hosted in the
// same render process depending on the process model. Browser objects created
// indirectly via the JavaScript window.open function or targeted links will
// share the same render process and the same request context as the source
// browser. When running in single-process mode there is only a single render
// process (the main process) and so all browsers created in single-process mode
// will share the same request context. This will be the first request context
// passed into a cef_browser_host_t static factory function and all other
// request context objects will be ignored.
//
pub struct CefRequestContext {
  c_object: *mut cef_request_context_t,
}

impl Clone for CefRequestContext {
  fn clone(&self) -> CefRequestContext{
    unsafe {
      if !self.c_object.is_null() {
        ((*self.c_object).base.add_ref.unwrap())(&mut (*self.c_object).base);
      }
      CefRequestContext {
        c_object: self.c_object,
      }
    }
  }
}

impl Drop for CefRequestContext {
  fn drop(&mut self) {
    unsafe {
      if !self.c_object.is_null() {
        ((*self.c_object).base.release.unwrap())(&mut (*self.c_object).base);
      }
    }
  }
}

impl CefRequestContext {
  pub unsafe fn from_c_object(c_object: *mut cef_request_context_t) -> CefRequestContext {
    CefRequestContext {
      c_object: c_object,
    }
  }

  pub unsafe fn from_c_object_addref(c_object: *mut cef_request_context_t) -> CefRequestContext {
    if !c_object.is_null() {
      ((*c_object).base.add_ref.unwrap())(&mut (*c_object).base);
    }
    CefRequestContext {
      c_object: c_object,
    }
  }

  pub fn c_object(&self) -> *mut cef_request_context_t {
    self.c_object
  }

  pub fn c_object_addrefed(&self) -> *mut cef_request_context_t {
    unsafe {
      if !self.c_object.is_null() {
        eutil::add_ref(self.c_object as *mut types::cef_base_t);
      }
      self.c_object
    }
  }

  pub fn is_null_cef_object(&self) -> bool {
    self.c_object.is_null()
  }
  pub fn is_not_null_cef_object(&self) -> bool {
    !self.c_object.is_null()
  }

  //
  // Returns true (1) if this object is pointing to the same context as |that|
  // object.
  //
  pub fn is_same(&self, other: interfaces::CefRequestContext) -> libc::c_int {
    if self.c_object.is_null() {
      panic!("called a CEF method on a null object")
    }
    unsafe {
      CefWrap::to_rust(
        ((*self.c_object).is_same.unwrap())(
          self.c_object,
          CefWrap::to_c(other)))
    }
  }

  //
  // Returns true (1) if this object is the global context.
  //
  pub fn is_global(&self) -> libc::c_int {
    if self.c_object.is_null() {
      panic!("called a CEF method on a null object")
    }
    unsafe {
      CefWrap::to_rust(
        ((*self.c_object).is_global.unwrap())(
          self.c_object))
    }
  }

  //
  // Returns the handler for this context if any.
  //
  pub fn get_handler(&self) -> interfaces::CefRequestContextHandler {
    if self.c_object.is_null() {
      panic!("called a CEF method on a null object")
    }
    unsafe {
      CefWrap::to_rust(
        ((*self.c_object).get_handler.unwrap())(
          self.c_object))
    }
  }

  //
  // Returns the global context object.
  //
  pub fn get_global_context() -> interfaces::CefRequestContext {
    unsafe {
      CefWrap::to_rust(
        ::request_context::cef_request_context_get_global_context(
))
    }
  }

  //
  // Creates a new context object with the specified handler.
  //
  pub fn create_context(
      handler: interfaces::CefRequestContextHandler) -> interfaces::CefRequestContext {
    unsafe {
      CefWrap::to_rust(
        ::request_context::cef_request_context_create_context(
          CefWrap::to_c(handler)))
    }
  }
} 

impl CefWrap<*mut cef_request_context_t> for CefRequestContext {
  fn to_c(rust_object: CefRequestContext) -> *mut cef_request_context_t {
    rust_object.c_object_addrefed()
  }
  unsafe fn to_rust(c_object: *mut cef_request_context_t) -> CefRequestContext {
    CefRequestContext::from_c_object_addref(c_object)
  }
}
impl CefWrap<*mut cef_request_context_t> for Option<CefRequestContext> {
  fn to_c(rust_object: Option<CefRequestContext>) -> *mut cef_request_context_t {
    match rust_object {
      None => ptr::null_mut(),
      Some(rust_object) => rust_object.c_object_addrefed(),
    }
  }
  unsafe fn to_rust(c_object: *mut cef_request_context_t) -> Option<CefRequestContext> {
    if c_object.is_null() {
      None
    } else {
      Some(CefRequestContext::from_c_object_addref(c_object))
    }
  }
}

