// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.drawImage.9arg.destpos
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

promise_test(async t => {
  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  const response_red = await fetch('/images/red.png');
  const blob_red = await response_red.blob();
  const bitmap_red = await createImageBitmap(blob_red);

  const response_green = await fetch('/images/green.png');
  const blob_green = await response_green.blob();
  const bitmap_green = await createImageBitmap(blob_green);

  ctx.drawImage(bitmap_green, 0, 0, 100, 50, 0, 0, 100, 50);
  ctx.drawImage(bitmap_green, 0, 0, 100, 50, -100, 0, 100, 50);
  ctx.drawImage(bitmap_red, 0, 0, 100, 50, 100, 0, 100, 50);
  ctx.drawImage(bitmap_red, 0, 0, 100, 50, 0, -50, 100, 50);
  ctx.drawImage(bitmap_red, 0, 0, 100, 50, 0, 50, 100, 50);
  _assertPixelApprox(canvas, 0,0, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 99,0, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 0,49, 0,255,0,255, 2);
  _assertPixelApprox(canvas, 99,49, 0,255,0,255, 2);
}, "");
done();
