/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

use std::ffi::CStr;
use std::ptr;

use js::jsapi::{CallArgs, JSFunctionSpec, JSObject};
use js::rooted;
use js::rust::HandleObject;
use js::rust::wrappers2::{GetRealmObjectPrototype, JS_NewPlainObject};

use crate::DomTypes;
use crate::codegen::PrototypeList;
use crate::constant::ConstantSpec;
use crate::error::throw_constructor_without_new;
use crate::guard::Guard;
use crate::interface::{create_callback_interface_object, get_desired_proto};
use crate::js::rust::GCMethods;
use crate::namespace::{NamespaceObjectClass, create_namespace_object};
use crate::utils::ProtoOrIfaceArray;

pub(crate) unsafe fn call_default_constructor<D: crate::DomTypes>(
    cx: &mut js::context::JSContext,
    args: &CallArgs,
    global: &D::GlobalScope,
    proto_id: PrototypeList::ID,
    ctor_name: &str,
    creator: unsafe fn(&mut js::context::JSContext, HandleObject, *mut ProtoOrIfaceArray),
    constructor: impl FnOnce(
        &mut js::context::JSContext,
        &CallArgs,
        &D::GlobalScope,
        HandleObject,
    ) -> bool,
) -> bool {
    if !args.is_constructing() {
        throw_constructor_without_new(cx.into(), ctor_name);
        return false;
    }

    rooted!(&in(cx) let mut desired_proto = ptr::null_mut::<JSObject>());
    let proto_result = get_desired_proto(cx, args, proto_id, creator, desired_proto.handle_mut());
    if proto_result.is_err() {
        return false;
    }

    constructor(cx, args, global, desired_proto.handle())
}

pub(crate) struct NamespaceInit {
    pub(crate) is_proto_hack: bool,
    pub(crate) static_methods: &'static [Guard<&'static [JSFunctionSpec]>],
    pub(crate) namespace_object_class: &'static NamespaceObjectClass,
    pub(crate) constructor_name: PrototypeList::Constructor,
    pub(crate) constants: &'static [Guard<&'static [ConstantSpec]>],
    pub(crate) name: &'static CStr,
}

pub(crate) struct CallbackInit {
    pub(crate) constants: &'static [Guard<&'static [ConstantSpec]>],
    pub(crate) p_name: PrototypeList::Constructor,
    pub(crate) name: &'static CStr,
}

pub(crate) enum ConstructorType {
    Namespace(NamespaceInit),
    Callback(CallbackInit),
}

pub(crate) struct CreateInterfaceObjectsOptions {
    pub(crate) constructor_type: ConstructorType,
}

/// This is a direct partial port of the `CreateInterfaceObjects` function generated by python code.
#[expect(non_snake_case)]
pub(crate) unsafe fn CreateInterfaceObjectsRust<D: DomTypes>(
    cx: &mut js::context::JSContext,
    init: CreateInterfaceObjectsOptions,
    global: HandleObject,
    cache: *mut ProtoOrIfaceArray,
) {
    unsafe {
        if let ConstructorType::Namespace(namespace_init) = init.constructor_type {
            rooted!(&in(cx) let mut proto: *mut JSObject = std::ptr::null_mut());
            if namespace_init.is_proto_hack {
                proto.set(GetRealmObjectPrototype(cx))
            } else {
                proto.set(JS_NewPlainObject(cx))
            };

            assert!(!proto.is_null());
            rooted!(&in(cx) let mut namespace = ptr::null_mut::<JSObject>());
            create_namespace_object::<D>(
                cx.into(),
                global,
                proto.handle(),
                namespace_init.namespace_object_class,
                namespace_init.static_methods,
                namespace_init.constants,
                namespace_init.name,
                namespace.handle_mut(),
            );
            assert!(!namespace.is_null());

            assert!((*cache)[namespace_init.constructor_name as usize].is_null());
            (*cache)[namespace_init.constructor_name as usize] = namespace.get();
            <*mut JSObject>::post_barrier(
                (*cache)
                    .as_mut_ptr()
                    .offset(namespace_init.constructor_name as isize),
                ptr::null_mut(),
                namespace.get(),
            );
        } else if let ConstructorType::Callback(cb_init) = init.constructor_type {
            rooted!(&in(cx) let mut interface = ptr::null_mut::<JSObject>());
            create_callback_interface_object::<D>(
                cx.into(),
                global,
                cb_init.constants,
                cb_init.name,
                interface.handle_mut(),
            );
            assert!(!interface.is_null());
            assert!((*cache)[cb_init.p_name as usize].is_null());
            (*cache)[cb_init.p_name as usize] = interface.get();
            <*mut JSObject>::post_barrier(
                (*cache).as_mut_ptr().offset(cb_init.p_name as isize),
                ptr::null_mut(),
                interface.get(),
            );
        }
        // Currently the rest of the initialization code is generated by codegen.py
    }
}
