[Constructor(optional AccelerometerSensorOptions options), SecureContext,
  Exposed=Window]
interface Accelerometer : Sensor {
  readonly attribute double? x;
  readonly attribute double? y;
  readonly attribute double? z;
};

enum LocalCoordinateSystem { "device", "screen" };

dictionary AccelerometerSensorOptions : SensorOptions {
  LocalCoordinateSystem referenceFrame = "device";
};

[Constructor(optional AccelerometerSensorOptions options), SecureContext,
  Exposed=Window]
interface LinearAccelerationSensor : Accelerometer {
};

[Constructor(optional AccelerometerSensorOptions options), SecureContext,
  Exposed=Window]
interface GravitySensor : Accelerometer {
};
