// https://github.com/wicg/trusted-types

typedef (DOMString or TrustedHTML) HTMLString;
typedef (DOMString or TrustedScript) ScriptString;
typedef (DOMString or TrustedScriptURL) ScriptURLString;
typedef (USVString or TrustedURL) URLString;

[Exposed=Window]
interface TrustedHTML {
    stringifier;
};

[Exposed=Window]
interface TrustedScript {
    stringifier;
};

[Exposed=Window]
interface TrustedScriptURL {
    stringifier;
};

[Exposed=Window]
interface TrustedURL {
    stringifier;
};

[Exposed=Window]
interface TrustedTypePolicyFactory {
    TrustedTypePolicy createPolicy(DOMString policyName, TrustedTypePolicyOptions policyOptions);
    // All the policy object names that have been created
    sequence<DOMString> getPolicyNames();
};

[Exposed=Window]
interface TrustedTypePolicy {
    readonly attribute DOMString name;
    TrustedHTML createHTML(DOMString input);
    TrustedScript createScript(DOMString input);
    TrustedScriptURL createScriptURL(DOMString input);
    TrustedURL createURL(DOMString input);
};

dictionary TrustedTypePolicyOptions {
   CreateHTMLCallback createHTML;
   CreateScriptCallback createScript;
   CreateURLCallback createScriptURL;
   CreateURLCallback createURL;
};

callback CreateHTMLCallback = DOMString (DOMString input);
callback CreateScriptCallback = DOMString (DOMString input);
callback CreateURLCallback = USVString (DOMString input);
