ifeq (androideabi,$(findstring androideabi,$(TARGET)))

CXX := $(TARGET)-g++
AR := $(TARGET)-ar
CFLAGS := -fPIC -O2

else

CXX ?= g++
AR ?= ar

endif

CSRC := src/native_window_glue.cpp

OBJS := $(CSRC:%.cpp=$(OUT_DIR)/%.o)

.PHONY: all
all: $(OUT_DIR)/libnative_window_glue.a

$(OUT_DIR)/%.o: %.cpp
	mkdir -p `dirname $@` && $(CXX) $< -o $@ -c $(CXXFLAGS) $(CPPFLAGS)

$(OUT_DIR)/libnative_window_glue.a: $(OBJS)
	$(AR) rcs $@ $<
