brew "autoconf@2.13"
brew "automake"
brew "cmake"
brew "openssl"
brew "pkg-config"
brew "gstreamer"
brew "gst-plugins-base", args: ["with-orc", "with-libogg", "with-opus", "with-theora", "with-libvorbis", "with-pango"]
brew "gst-libav"
brew "gst-plugins-bad"
brew "gst-plugins-good"
brew "gst-rtsp-server"
brew "llvm"
brew "yasm"

# For sccache
brew "openssl@1.1"
