/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

use unicode_script::Script;

// TODO(ddesyatkin):
// This intendedto be temporary solution. We should replace Unicode script property
// to the structures that ICU icu_locid crate provides
// https://crates.io/crates/icu_locid/0.4.0

// Then we must find the way of converting loc.id.script to unicode_script property

pub(super) fn iso15924_to_unicode_script(input_script_str: &str) -> Option<Script> {
    // Harmony OS have ISO15924 naming standart. Some additional conversion required.
    let script_str = match input_script_str {
        // Values bellow are taken from table under following link:
        // https://unicode.org/iso15924/iso15924-codes.html
        "Adlm" => "Adlam",
        "Aghb" => "Caucasian_Albanian",
        "Ahom" => "Ahom",
        "Arab" => "Arabic",
        "Armi" => "Imperial_Aramaic",
        "Armn" => "Armenian",
        "Avst" => "Avestan",
        "Bali" => "Balinese",
        "Bamu" => "Bamum",
        "Bass" => "Bassa_Vah",
        "Batk" => "Batak",
        "Beng" => "Bengali",
        "Bhks" => "Bhaiksuki",
        "Bopo" => "Bopomofo",
        "Brah" => "Brahmi",
        "Brai" => "Braille",
        "Bugi" => "Buginese",
        "Buhd" => "Buhid",
        "Cakm" => "Chakma",
        "Cans" => "Canadian_Aboriginal",
        "Cari" => "Carian",
        "Cham" => "Cham",
        "Cher" => "Cherokee",
        "Chrs" => "Chorasmian",
        "Copt" => "Coptic",
        "Cpmn" => "Cypro_Minoan",
        "Cprt" => "Cypriot",
        "Cyrl" => "Cyrillic",
        "Deva" => "Devanagari",
        "Diak" => "Dives_Akuru",
        "Dogr" => "Dogra",
        "Dsrt" => "Deseret",
        "Dupl" => "Duployan",
        "Egyp" => "Egyptian_Hieroglyphs",
        "Elba" => "Elbasan",
        "Elym" => "Elymaic",
        "Ethi" => "Ethiopic",
        "Gara" => "Garay",
        "Geok" => "Georgian",
        "Geor" => "Georgian",
        "Glag" => "Glagolitic",
        "Gong" => "Gunjala_Gondi",
        "Gonm" => "Masaram_Gondi",
        "Goth" => "Gothic",
        "Gran" => "Grantha",
        "Grek" => "Greek",
        "Gujr" => "Gujarati",
        "Gukh" => "Gurung_Khema",
        "Guru" => "Gurmukhi",
        "Hang" => "Hangul",
        "Hani" => "Han",
        "Hano" => "Hanunoo",
        "Hatr" => "Hatran",
        "Hebr" => "Hebrew",
        "Hira" => "Hiragana",
        "Hluw" => "Anatolian_Hieroglyphs",
        "Hmng" => "Pahawh_Hmong",
        "Hmnp" => "Nyiakeng_Puachue_Hmong",
        "Hrkt" => "Katakana_Or_Hiragana",
        "Hung" => "Old_Hungarian",
        "Ital" => "Old_Italic",
        "Java" => "Javanese",
        "Kali" => "Kayah_Li",
        "Kana" => "Katakana",
        "Kawi" => "Kawi",
        "Khar" => "Kharoshthi",
        "Khmr" => "Khmer",
        "Khoj" => "Khojki",
        "Kits" => "Khitan_Small_Script",
        "Knda" => "Kannada",
        "Krai" => "Kirat_Rai",
        "Kthi" => "Kaithi",
        "Lana" => "Tai_Tham",
        "Laoo" => "Lao",
        "Latn" => "Latin",
        "Lepc" => "Lepcha",
        "Limb" => "Limbu",
        "Lina" => "Linear_A",
        "Linb" => "Linear_B",
        "Lisu" => "Lisu",
        "Lyci" => "Lycian",
        "Lydi" => "Lydian",
        "Mahj" => "Mahajani",
        "Maka" => "Makasar",
        "Mand" => "Mandaic",
        "Mani" => "Manichaean",
        "Marc" => "Marchen",
        "Medf" => "Medefaidrin",
        "Mend" => "Mende_Kikakui",
        "Merc" => "Meroitic_Cursive",
        "Mero" => "Meroitic_Hieroglyphs",
        "Mlym" => "Malayalam",
        "Modi" => "Modi",
        "Mong" => "Mongolian",
        "Mroo" => "Mro",
        "Mtei" => "Meetei_Mayek",
        "Mult" => "Multani",
        "Mymr" => "Myanmar",
        "Nagm" => "Nag_Mundari",
        "Nand" => "Nandinagari",
        "Narb" => "Old_North_Arabian",
        "Nbat" => "Nabataean",
        "Newa" => "Newa",
        "Nkoo" => "Nko",
        "Nshu" => "Nushu",
        "Ogam" => "Ogham",
        "Olck" => "Ol_Chiki",
        "Onao" => "Ol_Onal",
        "Orkh" => "Old_Turkic",
        "Orya" => "Oriya",
        "Osge" => "Osage",
        "Osma" => "Osmanya",
        "Ougr" => "Old_Uyghur",
        "Palm" => "Palmyrene",
        "Pauc" => "Pau_Cin_Hau",
        "Perm" => "Old_Permic",
        "Phag" => "Phags_Pa",
        "Phli" => "Inscriptional_Pahlavi",
        "Phlp" => "Psalter_Pahlavi",
        "Phnx" => "Phoenician",
        "Plrd" => "Miao",
        "Prti" => "Inscriptional_Parthian",
        "Rjng" => "Rejang",
        "Rohg" => "Hanifi_Rohingya",
        "Runr" => "Runic",
        "Samr" => "Samaritan",
        "Sarb" => "Old_South_Arabian",
        "Saur" => "Saurashtra",
        "Sgnw" => "SignWriting",
        "Shaw" => "Shavian",
        "Shrd" => "Sharada",
        "Sidd" => "Siddham",
        "Sind" => "Khudawadi",
        "Sinh" => "Sinhala",
        "Sogd" => "Sogdian",
        "Sogo" => "Old_Sogdian",
        "Sora" => "Sora_Sompeng",
        "Soyo" => "Soyombo",
        "Sund" => "Sundanese",
        "Sunu" => "Sunuwar",
        "Sylo" => "Syloti_Nagri",
        "Syrc" => "Syriac",
        "Tagb" => "Tagbanwa",
        "Takr" => "Takri",
        "Tale" => "Tai_Le",
        "Talu" => "New_Tai_Lue",
        "Taml" => "Tamil",
        "Tang" => "Tangut",
        "Tavt" => "Tai_Viet",
        "Telu" => "Telugu",
        "Tfng" => "Tifinagh",
        "Tglg" => "Tagalog",
        "Thaa" => "Thaana",
        "Thai" => "Thai",
        "Tibt" => "Tibetan",
        "Tirh" => "Tirhuta",
        "Tnsa" => "Tangsa",
        "Todr" => "Todhri",
        "Toto" => "Toto",
        "Tutg" => "Tulu_Tigalari",
        "Ugar" => "Ugaritic",
        "Vaii" => "Vai",
        "Vith" => "Vithkuqi",
        "Wara" => "Warang_Citi",
        "Wcho" => "Wancho",
        "Xpeo" => "Old_Persian",
        "Xsux" => "Cuneiform",
        "Yezi" => "Yezidi",
        "Yiii" => "Yi",
        "Zanb" => "Zanabazar_Square",
        "Zinh" => "Inherited",
        "Zyyy" => "Common",
        "Zzzz" => "Unknown",
        // Some additional value necessary for OpenHarmony
        // https://www.unicode.org/reports/tr24/#Script_Values_Table
        "Hans" => "Han",
        "Hant" => "Han",
        "Syrj" => "Syriac",
        "Syrn" => "Syriac",
        "Syre" => "Syriac",
        "Cyrs" => "Cyrillic",
        "Latf" => "Latin",
        "Latg" => "Latin",
        // Default falue
        _ => "",
    };
    Script::from_full_name(script_str)
}
