[versions]
android-gradle-plugin = "9.2.1"
# The `minSdk` configuration affects both the `NDK` version we require,
# and the `minSdk` version for the gradle build.
# This value should only be bumped if necessary, and after discussion
# on zulip, since it directly affects the amount of people able to use
# servo on android.
# ATTENTION - READ THE COMMENT ABOVE, if the minSdk value below is changed.
android-sdk-min = "29"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.13.0" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version = "1.12.0" }
androidx-material3-compose = { module = "androidx.compose.material3:material3", version = "1.4.0" }
androidx-material3-compose-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version = "1.2.0" }
androidx-preference = { module = "androidx.preference:preference-ktx", version = "1.2.1" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version = "2.4.0" }
