[profile.default]
# Print a slow warning after period, terminate unit-test after 4x period.
slow-timeout = { period = "5s", terminate-after = 4 }
status-level = "leak"

[profile.ci]
fail-fast = false

[profile.ci.junit]
path = "junit.xml"

# The default is to use the amount of cores on the host,
# which is not a good fit for mobile ohos devices.
[[profile.default.overrides]]
platform = 'cfg(target_env = "ohos")'
test-threads = 4
