// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.line.miter.acute
// Description:Miter joins are drawn correctly with acute angles
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

var t = async_test("Miter joins are drawn correctly with acute angles");
var t_pass = t.done.bind(t);
var t_fail = t.step_func(function(reason) {
    throw reason;
});
t.step(function() {

  var canvas = new OffscreenCanvas(100, 50);
  var ctx = canvas.getContext('2d');

  ctx.fillStyle = '#f00';
  ctx.fillRect(0, 0, 100, 50);

  ctx.lineWidth = 200;
  ctx.lineJoin = 'miter';

  ctx.strokeStyle = '#0f0';
  ctx.miterLimit = 2.614;
  ctx.beginPath();
  ctx.moveTo(100, 1000);
  ctx.lineTo(100, 100);
  ctx.lineTo(1000, 1000);
  ctx.stroke();

  ctx.strokeStyle = '#f00';
  ctx.miterLimit = 2.613;
  ctx.beginPath();
  ctx.moveTo(100, 1000);
  ctx.lineTo(100, 100);
  ctx.lineTo(1000, 1000);
  ctx.stroke();

  _assertPixel(canvas, 1,1, 0,255,0,255);
  _assertPixel(canvas, 48,1, 0,255,0,255);
  _assertPixel(canvas, 48,48, 0,255,0,255);
  _assertPixel(canvas, 1,48, 0,255,0,255);
  t.done();
});
done();
