[SecureContext]
interface mixin NavigatorIdle {
  readonly attribute IdleManager idle;
};

Navigator includes NavigatorIdle;
WorkerNavigator includes NavigatorIdle;

[
  SecureContext,
  Exposed=(Window,Worker)
] interface IdleManager {
  Promise<IdleStatus> query(optional IdleOptions options);
};

dictionary IdleOptions {
  unsigned long threshold;
};

[
  SecureContext,
  Exposed=(Window,Worker)
] interface IdleStatus : EventTarget {
  readonly attribute IdleState state;
  attribute EventHandler onchange;
};

[
  SecureContext,
  Exposed=(Window,Worker)
] interface IdleState {
  readonly attribute UserIdleState user;
  readonly attribute ScreenIdleState screen;
};

enum UserIdleState {
    "active",
    "idle"
};

enum ScreenIdleState {
    "locked",
    "unlocked"
};
