source "https://rubygems.org"
ruby '2.3.1'

gem 'rdf', github: "ruby-rdf/rdf", branch: 'develop'
gem 'rdf-rdfxml', github: "ruby-rdf/rdf-rdfxml", branch: 'develop'
gem 'linkeddata'

gem 'jsonlint'
gem 'rspec'
gem 'rake'

gem 'byebug'