// DO NOT EDIT! This test has been generated by /html/canvas/tools/gentest.py.
// OffscreenCanvas test in a worker:2d.state.saverestore.fillStyle
// Description:
// Note:

importScripts("/resources/testharness.js");
importScripts("/html/canvas/resources/canvas-tests.js");

test(t => {
  const canvas = new OffscreenCanvas(300, 150);
  const ctx = canvas.getContext('2d');

  const old = ctx.fillStyle;
  ctx.save();
  ctx.fillStyle = "#ff0000";
  ctx.restore();
  _assertSame(ctx.fillStyle, old, "ctx.fillStyle", "old");
}, "save()/restore() restores fillStyle, for a canvas of size (300, 150).");

test(t => {
  const canvas = new OffscreenCanvas(300, 150);
  const ctx = canvas.getContext('2d');

  ctx.fillStyle = "#ff0000";
  const old = ctx.fillStyle;
  // We're not interested in failures caused by get(set(x)) != x (e.g.
  // from rounding), so compare against `old` instead of "#ff0000".
  ctx.save();
  _assertSame(ctx.fillStyle, old, "ctx.fillStyle", "old");
  ctx.restore();
}, "save() does not modify fillStyle, for a canvas of size (300, 150).");

test(t => {
  const canvas = new OffscreenCanvas(0, 0);
  const ctx = canvas.getContext('2d');

  const old = ctx.fillStyle;
  ctx.save();
  ctx.fillStyle = "#ff0000";
  ctx.restore();
  _assertSame(ctx.fillStyle, old, "ctx.fillStyle", "old");
}, "save()/restore() restores fillStyle, for a canvas of size (0, 0).");

test(t => {
  const canvas = new OffscreenCanvas(0, 0);
  const ctx = canvas.getContext('2d');

  ctx.fillStyle = "#ff0000";
  const old = ctx.fillStyle;
  // We're not interested in failures caused by get(set(x)) != x (e.g.
  // from rounding), so compare against `old` instead of "#ff0000".
  ctx.save();
  _assertSame(ctx.fillStyle, old, "ctx.fillStyle", "old");
  ctx.restore();
}, "save() does not modify fillStyle, for a canvas of size (0, 0).");

done();
