name: Linux WPT Tests
on:
  workflow_call:
    inputs:
      profile:
        required: true
        type: string
      wpt-args:
        default: ""
        required: false
        type: string
      wpt-sync-from-upstream:
        default: false
        required: false
        type: boolean
      number-of-wpt-chunks:
        default: 20
        required: false
        type: number

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash
  GST_PLUGIN_FEATURE_RANK: pulsesink:NONE,alsasink:NONE,jacksink:NONE,fakesink:MAX
  INTERMITTENT_TRACKER_DASHBOARD_SECRET: ${{ !inputs.wpt-sync-from-upstream && secrets.INTERMITTENT_TRACKER_DASHBOARD_SECRET || '' }}
  INTERMITTENT_TRACKER_DASHBOARD_SECRET_PROD: ${{ !inputs.wpt-sync-from-upstream && secrets.INTERMITTENT_TRACKER_DASHBOARD_SECRET_PROD || '' }}
  INTERMITTENT_TRACKER_DASHBOARD_SECRET_STAGING: ${{ !inputs.wpt-sync-from-upstream && secrets.INTERMITTENT_TRACKER_DASHBOARD_SECRET_STAGING || '' }}
  WPT_ALWAYS_SUCCEED_ARG: "${{ inputs.wpt-sync-from-upstream && '--always-succeed' || '' }}"

jobs:
  # chunks:
  #   name: Generate chunks array
  #   runs-on: ubuntu-22.04
  #   outputs:
  #     chunks-array: ${{ steps.generate-chunks-array.outputs.result }}
  #   steps:
  #     - uses: actions/github-script@v7
  #       id: generate-chunks-array
  #       with:
  #         script: |
  #           return Array.from({length: ${{ inputs.number-of-wpt-chunks }}}, (_, i) => i + 1)

  # Runs the underlying job (“workload”) on a self-hosted runner if available,
  # with the help of a `runner-select` job and a `runner-timeout` job.
  # runner-select:
  #   uses: ./.github/workflows/self-hosted-runner-select.yml
  #   secrets: inherit
  #   with:
  #     github-hosted-runner-label: ubuntu-22.04
  #     self-hosted-image-name: servo-ubuntu2204
  #     force-github-hosted-runner: ${{ inputs.force-github-hosted-runner }}
  #     self-hosted-runner-count: 20
  #     request-policy-override: true
  # runner-timeout:
  #   needs:
  #     # - runner-select
  #     - start-chunker
  #   uses: ./.github/workflows/self-hosted-runner-timeout.yml
  #   secrets: inherit
  #   with:
  #     unique-id: ${{ needs.runner-select.outputs.unique-id }}
  #     is-self-hosted: ${{ fromJSON(needs.runner-select.outputs.is-self-hosted) }}

  # FIXME inlined due to workflow call depth limit
  runner-select:
    name: Select Runner
    runs-on: ubuntu-latest
    outputs:
      unique-id: ${{ steps.select.outputs.unique_id }}
      github-hosted-runner-label: ${{ steps.select.outputs.github_hosted_runner_label }}
      self-hosted-runner-label: ${{ steps.select.outputs.self_hosted_runner_label }}
      selected-runner-label: ${{ steps.select.outputs.selected_runner_label }}
      is-self-hosted: ${{ steps.select.outputs.is_self_hosted }}
      self-hosted-runner-count: ${{ steps.select.outputs.self_hosted_runner_count }}
    steps:
      - name: Select and reserve best available runner
        id: select
        run: |
          github_hosted_runner_label='ubuntu-22.04'
          self_hosted_image_name='servo-ubuntu2204'
          self_hosted_runner_scope='/orgs/${{ github.repository_owner }}/actions/runners'
          force_github_hosted_runner='false'
          self_hosted_runner_count='20'
          request_policy_override='true'

          # List of monitor servers
          set -euo pipefail \
            https://ci0.servo.org \
            https://ci1.servo.org \
            https://ci2.servo.org \
          # End of server list (do not remove this comment)

          fall_back_to_github_hosted() {
            echo 'Falling back to GitHub-hosted runner'
            echo "selected_runner_label=$github_hosted_runner_label" | tee -a $GITHUB_OUTPUT
            echo 'is_self_hosted=false' | tee -a $GITHUB_OUTPUT
            exit 0
          }

          # Generate a unique id that allows the workload job to find the runner
          # we are reserving for it (via runner labels), and allows the timeout
          # job to find the workload job run (via the job’s friendly name), even
          # if there are multiple instances in the workflow call tree.
          unique_id=$(uuidgen)
          echo "unique_id=$unique_id" | tee -a $GITHUB_OUTPUT

          # Disable self-hosted runners by creating a repository variable named
          # NO_SELF_HOSTED_RUNNERS with any non-empty value.
          # <https://github.com/servo/servo/settings/variables/actions>
          if [ -n '${{ vars.NO_SELF_HOSTED_RUNNERS }}' ]; then
            echo 'NO_SELF_HOSTED_RUNNERS is set!'
            fall_back_to_github_hosted
          fi

          if [ "$force_github_hosted_runner" = true ]; then
            echo 'inputs.force-github-hosted-runner is set!'
            fall_back_to_github_hosted
          fi

          if [ "$request_policy_override" = true ]; then
            # First request the policy overrides.
            remaining_runner_count=$self_hosted_runner_count
            received_runner_count=0
            for monitor_api_base_url in "$@"; do
              if [ $remaining_runner_count -eq 0 ]; then
                break
              fi
              # Use the monitor API to request a policy override.
              policy_override_url=$monitor_api_base_url/policy/override\?$self_hosted_image_name=$remaining_runner_count
              result=$(mktemp)
              echo
              echo Requesting policy override for up to $remaining_runner_count more runners
              echo POST "$policy_override_url"
              if curl -sS --fail-with-body --connect-timeout 5 --max-time 30 -X POST "$policy_override_url" \
                  -H 'Authorization: Bearer ${{ secrets.SERVO_CI_MONITOR_API_TOKEN }}' > $result \
                  && jq -e . $result > /dev/null; then
                cat $result
                echo
                result_count=$(jq -e --arg image $self_hosted_image_name '.profile_override_counts[$image]' $result)
                remaining_runner_count=$((remaining_runner_count - result_count))
                received_runner_count=$((received_runner_count + result_count))
              else
                cat $result
                echo
              fi
            done

            # We may receive fewer runners than we requested. If so, adjust our expectations accordingly.
            self_hosted_runner_count=$received_runner_count

            # Now wait for the runners to come up.
            start_time=$(date -u +\%s)
            while :; do
              now=$(date -u +\%s)
              if [ $((now - start_time)) -gt 60 ]; then
                echo 'Timeout waiting for policy overrides to deliver!'
                exit 1
              fi
              remaining_runner_count=$self_hosted_runner_count
              for monitor_api_base_url in "$@"; do
                if [ $remaining_runner_count -eq 0 ]; then
                  break
                fi
                get_policy_override_url=$monitor_api_base_url/policy/override
                echo GET "$get_policy_override_url"
                if curl -sS --fail-with-body --connect-timeout 5 --max-time 30 -X POST "$get_policy_override_url" \
                    -H 'Authorization: Bearer ${{ secrets.SERVO_CI_MONITOR_API_TOKEN }}' > $result \
                    && jq -e . $result > /dev/null; then
                  cat $result
                  echo
                  result_count=$(jq -e --arg image $self_hosted_image_name '.actual_runner_ids_by_profile_key[$image] | length' $result)
                  remaining_runner_count=$((remaining_runner_count - result_count))
                else
                  cat $result
                  echo
                fi
              done
              if [ $remaining_runner_count -eq 0 ]; then
                break
              fi
            done
          fi

          # Try to reserve as many runners as possible, up to the needed count,
          # from a random server, until we have enough runners.
          remaining_runner_count=$self_hosted_runner_count
          for monitor_api_base_url in $(printf \%s\\n "$@" | shuf); do
            if [ $remaining_runner_count -eq 0 ]; then
              break
            fi
            # Use the monitor API to reserve a runner. If we get an object with
            # runner details, we succeeded. If we get null, we failed.
            take_runner_url=$monitor_api_base_url/profile/$self_hosted_image_name/take/$remaining_runner_count\?unique_id=$unique_id\&qualified_repo=${{ github.repository }}\&run_id=${{ github.run_id }}
            result=$(mktemp)
            echo
            echo Need to reserve $remaining_runner_count runners
            echo POST "$take_runner_url"
            if curl -sS --fail-with-body --connect-timeout 5 --max-time 30 -X POST "$take_runner_url" \
                -H 'Authorization: Bearer ${{ secrets.SERVO_CI_MONITOR_API_TOKEN }}' > $result \
                && jq -e . $result > /dev/null; then
              cat $result
              echo
              result_count=$(jq -e length $result)
              remaining_runner_count=$((remaining_runner_count - result_count))
            else
              cat $result
              echo
            fi
          done

          echo
          echo
          if [ $remaining_runner_count -eq 0 ]; then
            echo "github_hosted_runner_label=$github_hosted_runner_label" | tee -a $GITHUB_OUTPUT
            echo "self_hosted_runner_label=$self_hosted_runner_label" | tee -a $GITHUB_OUTPUT
            echo "selected_runner_label=reserved-for:$unique_id" | tee -a $GITHUB_OUTPUT
            echo "selected_runner_label=reserved-for:$unique_id" | tee -a $GITHUB_OUTPUT
            echo 'is_self_hosted=true' | tee -a $GITHUB_OUTPUT
            echo "self_hosted_runner_count=$self_hosted_runner_count" | tee -a $GITHUB_OUTPUT
            exit 0
          else
            echo 'Not enough self-hosted runners available!'
            fall_back_to_github_hosted
          fi

  start-chunker:
    needs: runner-select
    runs-on: ubuntu-22.04
    outputs:
      total-chunks: ${{ steps.start-chunker.outputs.total_chunks }}
      secret-token: ${{ steps.start-chunker.outputs.secret_token }}
      matrix: ${{ steps.start-chunker.outputs.matrix }}
    steps:
      - id: start-chunker
        run: |
          unique_id=${{ needs.runner-select.outputs.unique-id }}
          github_hosted_runner_count=20
          self_hosted_runner_count=${{ needs.runner-select.outputs.self-hosted-runner-count }}
          total_chunks=$(((github_hosted_runner_count + self_hosted_runner_count) * 6))
          echo "total_chunks=$total_chunks" | tee -a $GITHUB_OUTPUT

          start_url=https://ci0.servo.org/chunker/start\?unique_id=$unique_id
          start_url=$start_url\&qualified_repo=${{ github.repository }}
          start_url=$start_url\&run_id=${{ github.run_id }}
          start_url=$start_url\&total_chunks=$total_chunks
          # Chunks must be non-zero. Chunk zero always exits without running any tests.
          runner=1
          matrix=
          i=1; while [ $i -le $github_hosted_runner_count ]; do
            start_url=$start_url\&runners[$runner]=github-hosted
            matrix=${matrix:+,}$matrix"{runner:$runner,\"runs-on\":\"${{ needs.runner-select.outputs.github-hosted-runner-label }}\"}"
            runner=$((runner + 1))
          done
          i=1; while [ $i -le $self_hosted_runner_count ]; do
            start_url=$start_url\&runners[$runner]=self-hosted
            matrix=${matrix:+,}$matrix"{runner:$runner,\"runs-on\":\"${{ needs.runner-select.outputs.self-hosted-runner-label }}\"}"
            runner=$((runner + 1))
          done
          echo "POST $start_url"
          secret_token=$(curl -gfsSX POST "$start_url")
          echo "secret_token=$secret_token" >> $GITHUB_OUTPUT
          echo "matrix=[$matrix]" >> $GITHUB_OUTPUT
  linux-wpt:
    name: WPT [${{ needs.runner-select.outputs.unique-id }}]
    runs-on: ${{ matrix.runs-on }}
    needs: [runner-select, start-chunker]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.start-chunker.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
        if: ${{ runner.environment != 'self-hosted' && github.event_name != 'pull_request_target' }}
      # This is necessary to checkout the pull request if this run was triggered via a
      # `pull_request_target` event.
      - uses: actions/checkout@v4
        if: ${{ runner.environment != 'self-hosted' && github.event_name == 'pull_request_target' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # Faster checkout for self-hosted runner that uses prebaked repo.
      - if: ${{ runner.environment == 'self-hosted' && github.event_name != 'pull_request_target' }}
        run: git fetch --depth=1 origin $GITHUB_SHA
      - if: ${{ runner.environment == 'self-hosted' && github.event_name == 'pull_request_target' }}
        run: git fetch --depth=1 origin ${{ github.event.pull_request.head.sha }}
      - if: ${{ runner.environment == 'self-hosted' }}
        # Same as `git switch --detach FETCH_HEAD`, but fixes up dirty working
        # trees, in case the runner image was baked with a dirty working tree.
        run: |
          git switch --detach
          git reset --hard FETCH_HEAD

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.profile }}-binary-linux
          path: ${{ inputs.profile }}-binary-linux
      - name: unPackage binary
        run: tar -xzf ${{ inputs.profile }}-binary-linux/target.tar.gz
      - name: Setup Python
        if: ${{ runner.environment != 'self-hosted' }}
        uses: ./.github/actions/setup-python
      - name: Bootstrap dependencies
        if: ${{ runner.environment != 'self-hosted' }}
        run: |
          sudo apt update
          sudo apt install -qy --no-install-recommends mesa-vulkan-drivers fonts-noto-cjk gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav
          # ./mach bootstrap --skip-lints
      - name: Sync from upstream WPT
        if: ${{ inputs.wpt-sync-from-upstream }}
        run: |
          ./mach update-wpt --sync --patch
      - name: Set timeout multiplier
        if: ${{ runner.environment != 'self-hosted' }}
        run: echo SERVO_WPT_TIMEOUT_MULTIPLIER=2 >> $GITHUB_ENV
      - name: Set timeout multiplier
        if: ${{ runner.environment == 'self-hosted' }}
        run: echo SERVO_WPT_TIMEOUT_MULTIPLIER=1 >> $GITHUB_ENV
      - name: Run tests
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p wpt-filtered-logs/linux
          mkdir -p wpt-full-logs/linux
          exit_status_file=$(mktemp)
          while :; do
            chunk_url=https://ci0.servo.org/chunker/take\?unique_id=${{ needs.runner-select.outputs.unique-id }}
            chunk_url=$chunk_url\&secret_token=${{ needs.start-chunker.outputs.secret-token }}
            chunk_url=$chunk_url\&runner=${{ matrix.runner }}
            chunk_id=$(curl -fsSX POST "$chunk_url")
            if [ "$chunk_id" = null ]; then
              break
            fi
            >&2 echo .
            >&2 echo .
            >&2 echo .
            >&2 echo "Got chunk $chunk_id (of ${{ needs.start-chunker.outputs.total-chunks }} chunks)"
            if ./mach test-wpt \
              $WPT_ALWAYS_SUCCEED_ARG \
              --${{ inputs.profile }} --processes $(nproc) --timeout-multiplier $SERVO_WPT_TIMEOUT_MULTIPLIER \
              --total-chunks ${{ needs.start-chunker.outputs.total-chunks }} --this-chunk $chunk_id \
              --log-raw wpt-full-logs/linux/raw/$chunk_id.log \
              --log-wptreport wpt-full-logs/linux/wptreport/$chunk_id.json \
              --log-raw-unexpected wpt-filtered-logs/linux/$chunk_id.log \
              --filter-intermittents wpt-filtered-logs/linux/$chunk_id.json \
              ${{ inputs.wpt-args }}; then
              :  # Do nothing
            else
              echo $? > $exit_status_file
            fi
          done
          exit $(cat $exit_status_file)
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Archive results (filtered)
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: wpt-filtered-logs-linux-${{ matrix.runner }}
          path: wpt-filtered-logs/*/
      - name: Archive results (full)
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: wpt-full-logs-linux-${{ matrix.runner }}
          path: wpt-full-logs/*/

  report-test-results:
    name: Process WPT Results
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: linux-wpt
    steps:
      - name: Merge logs (full)
        uses: actions/upload-artifact/merge@v4
        with:
          name: wpt-full-logs-linux
          pattern: wpt-full-logs-linux-*
          delete-merged: true
      # This job needs to be last. If no filtered results were uploaded, it will fail, but we want to merge other archives in that case.
      - name: Merge logs (filtered)
        uses: actions/upload-artifact/merge@v4
        with:
          name: wpt-filtered-logs-linux
          pattern: wpt-filtered-logs-linux-*
          delete-merged: true
      - uses: actions/checkout@v4
        if: ${{ !cancelled() && !inputs.wpt-sync-from-upstream }}
      - uses: actions/download-artifact@v4
        if: ${{ !cancelled() && !inputs.wpt-sync-from-upstream }}
        with:
          name: wpt-filtered-logs-linux
          path: results
      - name: Report results
        if: ${{ !cancelled() && !inputs.wpt-sync-from-upstream }}
        run: |
          etc/ci/report_aggregated_expected_results.py \
            --tag="linux-wpt" \
            results/linux/*.json
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESULTS: ${{ toJson(needs.*.result) }}
