name: Linux WPT Tests
on:
  workflow_call:
    inputs:
      profile:
        required: true
        type: string
      wpt-args:
        default: ""
        required: false
        type: string
      wpt-sync-from-upstream:
        default: false
        required: false
        type: boolean
      number-of-wpt-chunks:
        default: 20
        required: false
        type: number

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash
  GST_PLUGIN_FEATURE_RANK: pulsesink:NONE,alsasink:NONE,jacksink:NONE,fakesink:MAX
  INTERMITTENT_TRACKER_DASHBOARD_SECRET: ${{ !inputs.wpt-sync-from-upstream && secrets.INTERMITTENT_TRACKER_DASHBOARD_SECRET || '' }}
  INTERMITTENT_TRACKER_DASHBOARD_SECRET_PROD: ${{ !inputs.wpt-sync-from-upstream && secrets.INTERMITTENT_TRACKER_DASHBOARD_SECRET_PROD || '' }}
  INTERMITTENT_TRACKER_DASHBOARD_SECRET_STAGING: ${{ !inputs.wpt-sync-from-upstream && secrets.INTERMITTENT_TRACKER_DASHBOARD_SECRET_STAGING || '' }}
  WPT_ALWAYS_SUCCEED_ARG: "${{ inputs.wpt-sync-from-upstream && '--always-succeed' || '' }}"

jobs:
  # chunks:
  #   name: Generate chunks array
  #   runs-on: ubuntu-22.04
  #   outputs:
  #     chunks-array: ${{ steps.generate-chunks-array.outputs.result }}
  #   steps:
  #     - uses: actions/github-script@v7
  #       id: generate-chunks-array
  #       with:
  #         script: |
  #           return Array.from({length: ${{ inputs.number-of-wpt-chunks }}}, (_, i) => i + 1)
  unique-id:
    runs-on: ubuntu-22.04
    outputs:
      unique-id: ${{ steps.unique-id.outputs.unique_id }}
    steps:
      - id: unique-id
        run: |
          # Generate a unique id that allows the workload job to find the runner
          # we are reserving for it (via runner labels), and allows the timeout
          # job to find the workload job run (via the job’s friendly name), even
          # if there are multiple instances in the workflow call tree.
          unique_id=$(uuidgen)
          echo "unique_id=$unique_id" | tee -a $GITHUB_OUTPUT
  linux-wpt:
    name: WPT
    runs-on: ${{ matrix.runs-on }}
    needs: unique-id
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: 0
            runs-on: ubuntu-22.04
          - runner: 1
            runs-on: ubuntu-22.04
          - runner: 2
            runs-on: ubuntu-22.04
          - runner: 3
            runs-on: ubuntu-22.04
          - runner: 4
            runs-on: ubuntu-22.04
          - runner: 5
            runs-on: ubuntu-22.04
          - runner: 6
            runs-on: ubuntu-22.04
          - runner: 7
            runs-on: ubuntu-22.04
          - runner: 8
            runs-on: ubuntu-22.04
          - runner: 9
            runs-on: ubuntu-22.04
          - runner: 10
            runs-on: ubuntu-22.04
          - runner: 11
            runs-on: ubuntu-22.04
          - runner: 12
            runs-on: ubuntu-22.04
          - runner: 13
            runs-on: ubuntu-22.04
          - runner: 14
            runs-on: ubuntu-22.04
          - runner: 15
            runs-on: ubuntu-22.04
          - runner: 16
            runs-on: ubuntu-22.04
          - runner: 17
            runs-on: ubuntu-22.04
          - runner: 18
            runs-on: ubuntu-22.04
          - runner: 19
            runs-on: ubuntu-22.04
          # TODO: use self-hosted-runner-select.yml to reserve runners
          - runner: 20
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 21
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 22
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 23
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 24
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 25
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 26
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 27
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 28
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 29
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 30
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 31
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 32
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 33
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 34
            runs-on: self-hosted-image:ubuntu2204-wpt
          - runner: 35
            runs-on: self-hosted-image:ubuntu2204-wpt
    steps:
      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request_target'
      # This is necessary to checkout the pull request if this run was triggered via a
      # `pull_request_target` event.
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          ref: refs/pull/${{ github.event.number }}/head
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.profile }}-binary-linux
          path: ${{ inputs.profile }}-binary-linux
      - name: unPackage binary
        run: tar -xzf ${{ inputs.profile }}-binary-linux/target.tar.gz
      - name: Setup Python
        uses: ./.github/actions/setup-python
      - name: Bootstrap dependencies
        run: |
          sudo apt update
          sudo apt install -qy --no-install-recommends mesa-vulkan-drivers fonts-noto-cjk
          ./mach bootstrap --skip-lints
      - name: Sync from upstream WPT
        if: ${{ inputs.wpt-sync-from-upstream }}
        run: |
          ./mach update-wpt --sync --patch
      - name: Set timeout multiplier
        if: ${{ runner.environment != 'self-hosted' }}
        run: echo SERVO_WPT_TIMEOUT_MULTIPLIER=2 >> $GITHUB_ENV
      - name: Set timeout multiplier
        if: ${{ runner.environment == 'self-hosted' }}
        run: echo SERVO_WPT_TIMEOUT_MULTIPLIER=0.75 >> $GITHUB_ENV
      - name: Run tests
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p wpt-filtered-logs/linux
          mkdir -p wpt-full-logs/linux
          unique_id=${{ needs.unique-id.outputs.unique-id }}
          total_chunks=$(((20 + 16) * 6))
          exit_status_file=$(mktemp)
          while :; do
            chunk_id=$(curl -fsSX POST "https://ci0.servo.org/chunker/take?unique_id=$unique_id&total_chunks=$total_chunks&runs_on=${{ matrix.runs-on }}")
            if [ "$chunk_id" = null ]; then
              break
            fi
            >&2 echo .
            >&2 echo .
            >&2 echo .
            >&2 echo "Got chunk $chunk_id (of $total_chunks chunks)"
            if ./mach test-wpt \
              $WPT_ALWAYS_SUCCEED_ARG \
              --${{ inputs.profile }} --processes $(nproc) --timeout-multiplier $SERVO_WPT_TIMEOUT_MULTIPLIER \
              --total-chunks $total_chunks --this-chunk $chunk_id \
              --log-raw wpt-full-logs/linux/raw/$chunk_id.log \
              --log-wptreport wpt-full-logs/linux/wptreport/$chunk_id.json \
              --log-raw-unexpected wpt-filtered-logs/linux/$chunk_id.log \
              --filter-intermittents wpt-filtered-logs/linux/$chunk_id.json \
              ${{ inputs.wpt-args }}; then
              :  # Do nothing
            else
              echo $? > $exit_status_file
            fi
          done
          exit $(cat $exit_status_file)
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Archive results (filtered)
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: wpt-filtered-logs-linux-${{ matrix.runner }}
          path: wpt-filtered-logs/*/
      - name: Archive results (full)
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: wpt-full-logs-linux-${{ matrix.runner }}
          path: wpt-full-logs/*/

  report-test-results:
    name: Process WPT Results
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: linux-wpt
    steps:
      - name: Merge logs (full)
        uses: actions/upload-artifact/merge@v4
        with:
          name: wpt-full-logs-linux
          pattern: wpt-full-logs-linux-*
          delete-merged: true
      # This job needs to be last. If no filtered results were uploaded, it will fail, but we want to merge other archives in that case.
      - name: Merge logs (filtered)
        uses: actions/upload-artifact/merge@v4
        with:
          name: wpt-filtered-logs-linux
          pattern: wpt-filtered-logs-linux-*
          delete-merged: true
      - uses: actions/checkout@v4
        if: ${{ !cancelled() && !inputs.wpt-sync-from-upstream }}
      - uses: actions/download-artifact@v4
        if: ${{ !cancelled() && !inputs.wpt-sync-from-upstream }}
        with:
          name: wpt-filtered-logs-linux
          path: results
      - name: Report results
        if: ${{ !cancelled() && !inputs.wpt-sync-from-upstream }}
        run: |
          etc/ci/report_aggregated_expected_results.py \
            --tag="linux-wpt" \
            results/linux/*.json
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESULTS: ${{ toJson(needs.*.result) }}
