name: Publish to crates.io

on:
  workflow_dispatch:
env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash

jobs:
  publish-crates-io:
    name: 'Publish to crates.io'
    if: github.repository == 'servo/servo'
    environment:
      name: publish_crates_io
      deployment: false
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    env:
      SERVO_CRATES_IO_SLEEP_AFTER_PUBLISH_SECONDS: "30"
      SERVO_CRATES_IO_VERIFY_PUBLISHED_TIMEOUT_SECONDS: "300"
      SERVO_CRATES_IO_VERIFY_PUBLISHED_INTERVAL_SECONDS: "10"
    steps:
      - uses: actions/checkout@v6
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
        # Verification requires building, which is incredibly slow and also increases our attack surface.
        # If we decide for an extra verification, we should add a seperate job before this one, which
        # does a `dry-run` publish without any elevated permissions.
        run: |
          python3 etc/ci/publish_crates_io.py --no-verify
      # For a whole workspace publish the above step will run into the token expiry,
      # which the script handles by exiting (code 0) before the predicted expiry.
      # Other failures, will still cause the workflow to fail
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth2
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth2.outputs.token }}
        # Since we assume 2 tries (2*25 minutes) should be enough to publish our workspace,
        # add `--fail-on-timeout` so the workflow fails if the assumption is violated
        # Otherwise this does exactly the same as the above publish step.
        run: |
          python3 etc/ci/publish_crates_io.py --no-verify --fail-on-timeout
