name: Detect Self-hosted Runner Timeout
on:
  workflow_call:
    inputs:
      unique-id:
        required: true
        type: string
      is-self-hosted:
        required: true
        type: boolean
      timeout:
        description: Job timeout in seconds
        type: number
        default: 120
        required: false

jobs:
  # In the unlikely event a self-hosted runner was selected and reserved but it
  # goes down before the workload starts, cancel the workflow run.
  runner-timeout:
    if: ${{ inputs.is-self-hosted }}
    name: Detect Runner Timeout
    runs-on: ubuntu-latest
    steps:
      - name: Cancel if workload job is still queued
        run: |
          run_url=/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}
          export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          sleep_per_iteration=15
          timeout=${{ inputs.timeout }} 
          num_iterations=$(( timeout / sleep_per_iteration ))
          for in in $(seq 1..${num_iterations})
          do
            # Wait for a bit between each API call
            sleep ${sleep_per_iteration}
            job_status=$(gh api "$run_url/jobs" \
             | jq -er --arg id '${{ inputs.unique-id }}' \
               '.jobs[] | select(.name | contains("[" + $id + "]")) | .status')
            echo "Job status is ${job_status}."
            if [ "${job_status}" != queued ]; then
             echo 'Job is not queued anymore. Exiting timeout job'
             exit 0
            else
             echo "Retrying..."
            fi
          done
          echo 'Timeout waiting for runner assignment!'
          echo 'Hint: does this repo have permission to access the runner group?'
          echo 'Hint: https://github.com/organizations/servo/settings/actions/runner-groups'
          echo 'Note: This might happen sporadically if there are a lot of concurrent jobs'
          echo 'which are competing for the limited number of self-hosted runners'
          echo
          echo 'Cancelling workflow run'
          gh api "$run_url/cancel" --method POST
          exit 1
